import type { Locale } from "./locale";

export type SiteContent = ReturnType<typeof getContent>;

const content = {
  en: {
    brand: { name: "Fx Lab", tagline: "A digital presence that answers for itself." },
    illustrative: {
      short: "Illustrative",
      rating: "Illustrative rating",
      metrics: "Illustrative example",
    },
    nav: {
      home: "Home",
      about: "About",
      services: "Services",
      benefits: "Benefits",
      pricing: "Pricing",
      contact: "Contact",
      cta: "Get Started",
      tryDemo: "Try Demo",
      switchLanguageTitle: "Switch Language",
      menu: "Menu",
      close: "Close menu",
    },
    hero: {
      headline: "AI That Answers for Your Business",
      description: "Expert AI tech to elevate your business operations and inquiries. Let's take your revenue and digital presence further.",
      getStarted: "Get Started",
      tryDemo: "Try Demo",
      getStartedWhatsappText:
        "Hi Felix! I'm interested in your services. Can you tell me more about what you offer?",
      tryDemoWhatsappText:
        "Hi Felix! I'd like to see a demo of your AI website / WhatsApp bot.",
      ratingScore: "5.0",
      ratingText: "from 80+ reviews",
      welcome: "Se habla español · We speak Spanish too",
      bento: {
        clientsCount: "100+",
        clientsLabel: "Our Esteemed Clients & Partners",
        projectsCount: "1951+",
        projectsLabel: "Total Inquiries Handled",
        projectsPill: "8% monthly growth",
        yearsCount: "6+",
        yearsLabel: "Years of Dedicated Tech Experience",
        efficiencyTitle: "Achieve Optimal Efficiency and Boost Productivity",
      },
    },
    servicesHeading: "Efficient and Integrated Automation Services",
    servicesSubheading: "Simplify operations with our efficient, quality-focused AI services.",
    bentoServices: [
      {
        id: "website",
        title: "Website Design & Assembly",
        description: "A beautiful, fast website made just for your business — no messy templates. It loads in under a second and turns visitors into customers.",
      },
      {
        id: "bot",
        title: "Custom WhatsApp Bots",
        description: "A smart assistant that answers your WhatsApp messages day and night, books appointments, and helps you make sales while you sleep.",
      },
      {
        id: "leads",
        title: "Targeted Lead Generation",
        description: "We bring you people who are already interested in what you sell, so you spend time closing deals instead of chasing customers.",
      },
      {
        id: "tech",
        title: "Technology & AI Innovation",
        description: "We use modern AI tools to automate the repetitive work in your business, so you and your team can focus on what actually matters.",
      },
      {
        id: "sync",
        title: "Automated CRM & Sync",
        description: "Your appointments, invoices, and customer details move automatically between your calendar, email, and payment tools — no manual copying.",
      },
      {
        id: "consulting",
        title: "Strategic Growth Consulting",
        description: "Talk one-on-one with us. We look at how your business runs today and tell you exactly where technology can save you time and money.",
      },
    ],
    servicesBento: {
      badge: "CORE CAPABILITIES",
      flagshipBadge: "FLAGSHIP SERVICE",
      lighthouseScore: "Google Lighthouse Score",
      subSecondLoad: "⚡ Sub-second load time (<0.4s) • Zero AI Slop",
      activeBadge: "24/7 ACTIVE",
      chatCustomerMsg: "Hey! Are there any appointments available today?",
      chatBotReply: "Hi! Yes, we have 4:00 PM open. Booked & confirmed ✅",
      autoBookLabel: "AI Auto-Book",
      convBadge: "↗ +45% CONV",
      inboundFlowLabel: "Inbound Flow",
      prequalifiedLabel: "100% Pre-qualified",
      engineBadge: "GPT-4o ENGINE",
      modelLatencyLabel: "Model Latency",
      autoPipelineBadge: "AUTO PIPELINE",
      waLeadLabel: "WA Lead",
      calendarLabel: "Calendar",
      oneOnOneBadge: "1-ON-1 DIRECT",
      talkToFounder: "Talk to Founder",
    },
    statsStrip: {
      aiPoweredCore: "AI Powered Core",
    },
    benefits: {
      heading: "Why Businesses Choose Us",
      subheading: "Our systems save you time and money while your business keeps running — even when you're not there.",
      benefitCards: [
        {
          title: "Replies in seconds, day and night",
          description: "Your customers get an answer right away, 24/7 — no more missed messages or lost sales.",
        },
        {
          title: "Appointments book themselves",
          description: "Customers can check your availability and book a time, without you lifting a finger.",
        },
        {
          title: "Less busywork, more growth",
          description: "We automate the repetitive tasks so you can focus on serving customers and growing your business.",
        },
      ],
      pillars: [
        {
          title: "Answer every customer",
          description: "No one is left waiting. Every message gets a fast, friendly reply — even outside business hours.",
        },
        {
          title: "Save hours every day",
          description: "Stop copy-pasting and answering the same questions. The system handles it for you automatically.",
        },
        {
          title: "Turn chats into sales",
          description: "More answered inquiries means more bookings and more revenue — without hiring extra staff.",
        },
      ],
    },
    pricing: {
      badge: "TRANSPARENT VALUE",
      heading: "Simple Pricing & Tailored Packages",
      subheading: "Two services, each with its own price. Choose the one you need — or both.",
      starter: {
        name: "Custom Website",
        desc: "An ultra-fast, high-converting website built just for your business.",
        price: "$500",
        priceDetail: "one-time · plus ~$12/mo hosting",
        features: [
          "Handcrafted, high-speed website (no cheap templates)",
          "Google Lighthouse 99+ speed score",
          "Mobile-first conversion design & SEO",
          "Direct WhatsApp lead routing button",
          "Includes 30 days post-launch support",
        ],
        cta: "Get My Website",
      },
      bot: {
        name: "WhatsApp AI Bot",
        desc: "A smart assistant that answers your messages 24/7 and books appointments for you.",
        price: "Monthly",
        priceDetail: "Custom quote based on your needs",
        features: [
          "24/7 WhatsApp answers and lead capture",
          "Automatic appointment booking & calendar sync",
          "Continuous tuning and maintenance included",
          "Direct 1-on-1 priority support",
        ],
        cta: "Get a Quote",
      },
      configurator: {
        title: "Or Build Your Custom Package",
        subtitle: "Pick the tools your business needs and get a clear quote on WhatsApp in minutes.",
        cta: "Get Custom Quote on WhatsApp",
        modules: [
          { id: "web", name: "Custom Website", desc: "A fast, high-converting website built for your business.", type: "one-time", defaultChecked: true },
          { id: "whatsapp", name: "24/7 WhatsApp AI Bot", desc: "Instant answers, lead capture and automatic booking.", type: "monthly", defaultChecked: true },
          { id: "voice", name: "AI Voice Agent", desc: "Answers your phone calls and books appointments by voice.", type: "monthly", defaultChecked: false },
          { id: "crm", name: "CRM & Calendar Sync", desc: "Keeps your calendar, payments and contacts in sync automatically.", type: "monthly", defaultChecked: true },
          { id: "leads", name: "Targeted Leads", desc: "Brings you people already interested in what you offer.", type: "monthly", defaultChecked: false },
        ],
      },
      standaloneLabel: "One-time",
      monthlyLabel: "Monthly",
      includedLabel: "What's Included",
      botBenefitsLabel: "What's Included",
      configuratorBadge: "INTERACTIVE CONFIGURATOR",
      modulesSelectedSuffix: "services selected · we'll send your quote",
      starterWhatsappText: "Hi Felix! I'm interested in a Custom Website ($500).",
      botWhatsappText: "Hi Felix! I'm interested in the WhatsApp AI Bot. Can you send me a quote?",
      customWhatsappGreetingPrefix: "Hello Felix! I'm on your website and would like a custom package quote for my business. I'm interested in: ",
      customWhatsappGreetingSuffix: ".",
      defaultPackageLabel: "a custom package",
    },
    integrations: {
      heading: "Empowering Top Companies with Seamless Integrations",
      subheading: "Experience seamless connections with our innovative AI solutions, designed to effortlessly integrate with your existing systems and drive greater success.",
      cta: "Work With Us",
      badge: "NEURAL DATA FLOW",
      activeLabel: "Active",
      hoverHint: "Hover over each integration to see the data flow",
      items: {
        whatsapp: { role: "24/7 AI Sales & Lead Capture", badge: "Official API" },
        openai: { role: "Intelligent Reasoning Core", badge: "LLM Brain" },
        stripe: { role: "Instant Checkout & Subscriptions", badge: "Auto-Invoicing" },
        calendar: { role: "Automatic Meeting Booking", badge: "Auto-Sync" },
        meta: { role: "Lead Generation Pipeline", badge: "Traffic Flow" },
        crm: { role: "Centralized Client Database", badge: "Instant Sync" },
      },
    },
    about: {
      eyebrow: "Behind the Systems",
      heading: "Hi, I'm Felix",
      role: "Founder & Automation Specialist",
      bio: "I help local business owners stop spending their evenings answering the same messages. I build fast websites and 24/7 WhatsApp bots that book appointments and answer customers for you — so you can focus on the work you actually enjoy. No account managers, no big-agency runaround. You talk directly to the person building it.",
      trustPoints: [
        {
          title: "You talk to me, not a middleman",
          description: "Direct access to the founder who actually builds your project — no account managers.",
        },
        {
          title: "Fast, honest answers",
          description: "Clear communication without jargon or hidden fine print. You always know where things stand.",
        },
        {
          title: "Built for your business",
          description: "No generic templates. Everything is designed around how your business actually works.",
        },
      ],
      cta: "Let's Talk",
      whatsappText: "Hi Felix! I'd like to talk about working together.",
    },
    contact: {
      eyebrow: "Start Your Journey",
      directLine: "Direct Line",
      instantChatTitle: "Prefer instant chat?",
      instantChatBody: "Skip the form and message Felix directly on WhatsApp for an immediate response.",
      openWhatsapp: "Open WhatsApp",
      heading: "From Idea to Production in Days",
      subheading: "Ready to automate your inquiries and turn site traffic into booked clients? Send a message below or chat directly on WhatsApp.",
      welcome: "Se habla español · We speak Spanish too",
      name: "Name",
      contact: "Phone, WhatsApp, or email",
      businessType: "Business type",
      options: ["Restaurant", "Shop", "Contractor", "Other"],
      message: "Message",
      send: "Send",
      sending: "Sending...",
      success: "Thanks — I'll get back to you soon.",
      deliveryFailed: "Your message didn't go through. Please try again, or message Felix directly on WhatsApp.",
      formError: "Please fix the highlighted fields.",
      errors: {
        name: "Name is required",
        contact: "Enter a valid phone number or email",
        businessType: "Business type is required",
        message: "Please add a short message",
      },
    },
    footer: {
      tagline: "Our systems make your digital presence faster, smarter, and always online.",
      companyTitle: "Company",
      companyLinks: ["About Us", "Customers"],
      servicesTitle: "Services",
      servicesLinks: ["Website Engineering", "WhatsApp Bots", "Lead Generation", "AI Integrations"],
      getInTouchTitle: "Get in Touch",
      directWhatsapp: "Direct WhatsApp",
      callTitle: "Call",
      emailTitle: "Email",
      serviceArea: "San Diego · South Bay",
      terms: "Terms & Conditions",
      privacy: "Privacy Policy",
      copyright: `© ${new Date().getFullYear()} Fx Lab. All rights reserved.`,
    },
    bentoServicesCta: "Chat on WhatsApp",
    legal: {
      terms: {
        title: "Terms & Conditions",
        updated: "Last updated: September 2026",
        body: [
          "By submitting the contact form or hiring Fx Lab, you agree to these terms.",
          "Fx Lab designs and builds websites, WhatsApp bots, and related automation for local businesses. Project scope, pricing, and delivery timelines are agreed directly with Felix before work begins.",
          "One-time website packages include 30 days of post-launch support. Monthly retainer services (AI bots, voice agents) renew month to month and can be cancelled with notice via WhatsApp or email.",
          "Payments are due as agreed at project kickoff. Domain, hosting, and third-party subscription costs (if any) are billed separately and disclosed up front.",
          "Fx Lab is not liable for indirect or consequential damages arising from use of the delivered website or bot. Deliverables are provided as-is after acceptance testing.",
          "Questions about these terms can be sent to the contact below.",
        ],
      },
      privacy: {
        title: "Privacy Policy",
        updated: "Last updated: September 2026",
        body: [
          "This page explains what information the contact form collects and how it's used.",
          "When you submit the contact form, we collect your name, the contact method you provide (phone, WhatsApp, or email), your business type, and any message you write.",
          "That information is emailed directly to Felix to respond to your inquiry. It is not sold, shared with advertisers, or used for any purpose beyond replying to you and, if you become a client, delivering the agreed service.",
          "We use cookieless, privacy-friendly analytics (Vercel Web Analytics) to understand how visitors reach and use the site in aggregate. This does not track you across the web, does not use cookies, and collects no personally identifying information. We measure aggregate visits and a few conversion actions (for example, a click on a WhatsApp button or a submitted contact form) to know what is worth improving.",
          "To request deletion of your information, contact Felix by WhatsApp or email using the details in the footer, and it will be removed from our records.",
        ],
      },
    },
    language: "Español",
  },
  es: {
    brand: { name: "Fx Lab", tagline: "Una presencia digital que responde por sí sola." },
    illustrative: {
      short: "Ilustrativo",
      rating: "Valoración ilustrativa",
      metrics: "Ejemplo ilustrativo",
    },
    nav: {
      home: "Inicio",
      about: "Sobre Mí",
      services: "Servicios",
      benefits: "Beneficios",
      pricing: "Planes",
      contact: "Contacto",
      cta: "Comenzar",
      tryDemo: "Ver Demo",
      switchLanguageTitle: "Cambiar Idioma",
      menu: "Menú",
      close: "Cerrar menú",
    },
    hero: {
      headline: "IA Que Responde Por Tu Negocio",
      description: "Tecnología de IA de vanguardia para elevar las operaciones y consultas de tu negocio. Llevemos tus ingresos y presencia digital al siguiente nivel.",
      getStarted: "Comenzar",
      tryDemo: "Ver Demo",
      getStartedWhatsappText:
        "¡Hola Felix! Me interesan tus servicios. ¿Me cuentas más sobre lo que ofreces?",
      tryDemoWhatsappText:
        "¡Hola Felix! Me gustaría ver una demo de tu sitio web / bot de WhatsApp con IA.",
      ratingScore: "5.0",
      ratingText: "de más de 80 reseñas",
      welcome: "We speak English too · También hablamos español",
      bento: {
        clientsCount: "100+",
        clientsLabel: "Nuestros Clientes y Aliados",
        projectsCount: "1951+",
        projectsLabel: "Consultas y Leads Procesados",
        projectsPill: "8% crecimiento mensual",
        yearsCount: "6+",
        yearsLabel: "Años de Experiencia en Automatización",
        efficiencyTitle: "Alcanza la Máxima Eficiencia y Productividad",
      },
    },
    servicesHeading: "Servicios de Automatización Eficientes e Integrados",
    servicesSubheading: "Simplifica tus operaciones con nuestros servicios de IA enfocados en la calidad y conversión.",
    bentoServices: [
      {
        id: "website",
        title: "Diseño y Creación Web",
        description: "Un sitio web bonito y rápido hecho a la medida de tu negocio — sin plantillas genéricas. Carga en menos de un segundo y convierte visitas en clientes.",
      },
      {
        id: "bot",
        title: "Bots Personalizados de WhatsApp",
        description: "Un asistente inteligente que responde tus mensajes de WhatsApp día y noche, agenda citas y te ayuda a vender mientras duermes.",
      },
      {
        id: "leads",
        title: "Generación de Leads Calificados",
        description: "Te traemos personas que ya están interesadas en lo que vendes, para que dediques tu tiempo a cerrar ventas en vez de perseguir clientes.",
      },
      {
        id: "tech",
        title: "Tecnología e Innovación IA",
        description: "Usamos herramientas de IA modernas para automatizar el trabajo repetitivo de tu negocio, para que tú y tu equipo se concentren en lo importante.",
      },
      {
        id: "sync",
        title: "Sincronización de CRM y Calendario",
        description: "Tus citas, facturas y datos de clientes se mueven solos entre tu calendario, correo y herramientas de pago — sin copiar nada a mano.",
      },
      {
        id: "consulting",
        title: "Consultoría Estratégica de Crecimiento",
        description: "Habla directamente con nosotros. Revisamos cómo funciona tu negocio hoy y te decimos exactamente dónde la tecnología te ahorra tiempo y dinero.",
      },
    ],
    servicesBento: {
      badge: "CAPACIDADES CLAVE",
      flagshipBadge: "SERVICIO INSIGNIA",
      lighthouseScore: "Puntuación Google Lighthouse",
      subSecondLoad: "⚡ Carga en menos de 0.4s • Cero 'AI slop'",
      activeBadge: "24/7 ACTIVO",
      chatCustomerMsg: "¡Hola! ¿Tienen citas disponibles hoy?",
      chatBotReply: "¡Hola! Sí, tenemos las 4:00 PM libres. Reservado y confirmado ✅",
      autoBookLabel: "Auto-Reserva IA",
      convBadge: "↗ +45% CONV",
      inboundFlowLabel: "Flujo de Entrada",
      prequalifiedLabel: "100% Precalificado",
      engineBadge: "MOTOR GPT-4o",
      modelLatencyLabel: "Latencia del Modelo",
      autoPipelineBadge: "PIPELINE AUTOMÁTICO",
      waLeadLabel: "Lead WA",
      calendarLabel: "Calendario",
      oneOnOneBadge: "1 A 1 DIRECTO",
      talkToFounder: "Habla con el Fundador",
    },
    statsStrip: {
      aiPoweredCore: "Núcleo con IA",
    },
    benefits: {
      heading: "Por Qué Nos Eligen los Negocios",
      subheading: "Nuestros sistemas te ahorran tiempo y dinero mientras tu negocio sigue funcionando — incluso cuando no estás.",
      benefitCards: [
        {
          title: "Responde en segundos, día y noche",
          description: "Tus clientes reciben respuesta al instante, 24/7 — sin mensajes perdidos ni ventas que se escapan.",
        },
        {
          title: "Las citas se agendan solas",
          description: "Tus clientes revisan tu disponibilidad y reservan su cita, sin que tú muevas un dedo.",
        },
        {
          title: "Menos trabajo, más crecimiento",
          description: "Automatizamos las tareas repetitivas para que te enfoques en atender a tus clientes y crecer.",
        },
      ],
      pillars: [
        {
          title: "Atiende a cada cliente",
          description: "Nadie se queda esperando. Cada mensaje recibe una respuesta rápida y amable — incluso fuera de horario.",
        },
        {
          title: "Ahorra horas cada día",
          description: "Deja de copiar y pegar y de responder las mismas preguntas. El sistema lo hace por ti en automático.",
        },
        {
          title: "Convierte chats en ventas",
          description: "Más consultas respondidas significa más citas y más ingresos — sin contratar personal extra.",
        },
      ],
    },
    pricing: {
      badge: "VALOR TRANSPARENTE",
      heading: "Precios Transparentes y Paquetes a Medida",
      subheading: "Dos servicios, cada uno con su propio precio. Elige el que necesites — o ambos.",
      starter: {
        name: "Sitio Web a Medida",
        desc: "Un sitio web ultra rápido y de alta conversión, hecho a la medida de tu negocio.",
        price: "$500",
        priceDetail: "pago único · más ~$12/mes de hosting",
        features: [
          "Diseño web a mano y de alto rendimiento (sin plantillas baratas)",
          "Puntuación Google Lighthouse 99+",
          "Diseño móvil y optimización SEO local",
          "Botón de contacto directo a WhatsApp",
          "Incluye 30 días de soporte post-lanzamiento",
        ],
        cta: "Quiero mi Sitio Web",
      },
      bot: {
        name: "Bot de WhatsApp con IA",
        desc: "Un asistente inteligente que responde tus mensajes 24/7 y agenda citas por ti.",
        price: "Mensual",
        priceDetail: "Cotización según tus necesidades",
        features: [
          "Respuestas en WhatsApp y captación de leads 24/7",
          "Agendamiento automático de citas y sincronización con calendario",
          "Ajuste y mantenimiento continuo incluido",
          "Soporte directo 1 a 1 prioritario",
        ],
        cta: "Pedir Cotización",
      },
      configurator: {
        title: "O Diseña Tu Propio Paquete a Medida",
        subtitle: "Elige las herramientas que necesita tu negocio y recibe una cotización clara por WhatsApp en minutos.",
        cta: "Pedir Cotización en WhatsApp",
        modules: [
          { id: "web", name: "Sitio Web a Medida", desc: "Un sitio rápido y de alta conversión hecho para tu negocio.", type: "one-time", defaultChecked: true },
          { id: "whatsapp", name: "Bot de WhatsApp 24/7 con IA", desc: "Respuestas al instante, captación de leads y citas automáticas.", type: "monthly", defaultChecked: true },
          { id: "voice", name: "Agente de Voz IA", desc: "Atiende tus llamadas y agenda citas por voz.", type: "monthly", defaultChecked: false },
          { id: "crm", name: "Sincronización CRM y Calendario", desc: "Mantiene tu calendario, pagos y contactos sincronizados en automático.", type: "monthly", defaultChecked: true },
          { id: "leads", name: "Captación de Clientes", desc: "Te trae personas que ya están interesadas en lo que ofreces.", type: "monthly", defaultChecked: false },
        ],
      },
      standaloneLabel: "Pago único",
      monthlyLabel: "Mensual",
      includedLabel: "Qué Incluye",
      botBenefitsLabel: "Qué Incluye",
      configuratorBadge: "CONFIGURADOR INTERACTIVO",
      modulesSelectedSuffix: "servicios seleccionados · te enviamos tu cotización",
      starterWhatsappText: "¡Hola Felix! Me interesa un Sitio Web a Medida ($500).",
      botWhatsappText: "¡Hola Felix! Me interesa el Bot de WhatsApp con IA. ¿Me envías una cotización?",
      customWhatsappGreetingPrefix: "¡Hola Felix! Estoy en tu sitio web y me gustaría una cotización de paquete personalizado para mi negocio. Me interesa: ",
      customWhatsappGreetingSuffix: ".",
      defaultPackageLabel: "un paquete personalizado",
    },
    integrations: {
      heading: "Potenciando Negocios con Integraciones Fluidas",
      subheading: "Conecta sin esfuerzo tus sistemas actuales con nuestras soluciones de IA para aumentar la productividad y el éxito de tu negocio.",
      cta: "Trabaja con Nosotros",
      badge: "FLUJO NEURAL DE DATOS",
      activeLabel: "Activo",
      hoverHint: "Pasa el cursor sobre cada integración para ver el flujo de datos",
      items: {
        whatsapp: { role: "Ventas IA y Captación de Leads 24/7", badge: "API Oficial" },
        openai: { role: "Núcleo de Razonamiento IA", badge: "Cerebro LLM" },
        stripe: { role: "Pagos y Suscripciones Instantáneos", badge: "Facturación Automática" },
        calendar: { role: "Agendamiento Automático de Citas", badge: "Auto-Sincronización" },
        meta: { role: "Embudo de Generación de Leads", badge: "Flujo de Tráfico" },
        crm: { role: "Base de Datos Centralizada de Clientes", badge: "Sincronización Instantánea" },
      },
    },
    about: {
      eyebrow: "Detrás de los Sistemas",
      heading: "Hola, soy Felix",
      role: "Fundador y Especialista en Automatización",
      bio: "Ayudo a dueños de negocios locales a dejar de pasar las noches respondiendo los mismos mensajes. Construyo sitios web rápidos y bots de WhatsApp 24/7 que agendan citas y atienden a tus clientes por ti — para que te enfoques en el trabajo que de verdad disfrutas. Sin gerentes de cuenta ni vueltas de agencia grande. Hablas directo con la persona que lo construye.",
      trustPoints: [
        {
          title: "Hablas conmigo, no con un intermediario",
          description: "Acceso directo al fundador que construye tu proyecto — sin gerentes de cuenta.",
        },
        {
          title: "Respuestas rápidas y honestas",
          description: "Comunicación clara, sin jerga ni letra pequeña. Siempre sabes en qué punto va todo.",
        },
        {
          title: "Hecho para tu negocio",
          description: "Nada de plantillas genéricas. Todo se diseña según cómo funciona tu negocio en la práctica.",
        },
      ],
      cta: "Hablemos",
      whatsappText: "¡Hola Felix! Me gustaría hablar sobre trabajar juntos.",
    },
    contact: {
      eyebrow: "Comienza tu Camino",
      directLine: "Línea Directa",
      instantChatTitle: "¿Prefieres chat instantáneo?",
      instantChatBody: "Omite el formulario y escríbele a Felix directo por WhatsApp para una respuesta inmediata.",
      openWhatsapp: "Abrir WhatsApp",
      heading: "De la Idea a la Producción en Días",
      subheading: "¿Listo para automatizar tus consultas y convertir visitas en clientes? Envía un mensaje abajo o chatea directo por WhatsApp.",
      welcome: "We speak English too · También hablamos español",
      name: "Nombre",
      contact: "Teléfono, WhatsApp o correo",
      businessType: "Tipo de negocio",
      options: ["Restaurante", "Tienda", "Contratista", "Otro"],
      message: "Mensaje",
      send: "Enviar",
      sending: "Enviando...",
      success: "Gracias, te responderé pronto.",
      deliveryFailed: "Tu mensaje no se pudo enviar. Inténtalo de nuevo o escríbele a Felix directo por WhatsApp.",
      formError: "Corrige los campos marcados.",
      errors: {
        name: "El nombre es obligatorio",
        contact: "Ingresa un teléfono o correo válido",
        businessType: "El tipo de negocio es obligatorio",
        message: "Agrega un mensaje breve",
      },
    },
    footer: {
      tagline: "Nuestros sistemas hacen que tu presencia digital sea más rápida, inteligente y siempre activa.",
      companyTitle: "Empresa",
      companyLinks: ["Sobre Mí", "Clientes"],
      servicesTitle: "Servicios",
      servicesLinks: ["Ingeniería Web", "Bots de WhatsApp", "Generación de Leads", "Integraciones IA"],
      getInTouchTitle: "Contacto",
      directWhatsapp: "WhatsApp Directo",
      callTitle: "Llamar",
      emailTitle: "Correo",
      serviceArea: "San Diego · South Bay",
      terms: "Términos y Condiciones",
      privacy: "Política de Privacidad",
      copyright: `© ${new Date().getFullYear()} Fx Lab. Todos los derechos reservados.`,
    },
    bentoServicesCta: "Hablar por WhatsApp",
    legal: {
      terms: {
        title: "Términos y Condiciones",
        updated: "Última actualización: septiembre de 2026",
        body: [
          "Al enviar el formulario de contacto o contratar a Fx Lab, aceptas estos términos.",
          "Fx Lab diseña y construye sitios web, bots de WhatsApp y automatizaciones relacionadas para negocios locales. El alcance, precio y tiempos de entrega de cada proyecto se acuerdan directamente con Felix antes de comenzar el trabajo.",
          "Los paquetes de sitio web de pago único incluyen 30 días de soporte post-lanzamiento. Los servicios mensuales (bots de IA, agentes de voz) se renuevan mes a mes y pueden cancelarse avisando por WhatsApp o correo.",
          "Los pagos se realizan según lo acordado al inicio del proyecto. Costos de dominio, hosting o suscripciones de terceros (si aplican) se facturan por separado y se informan con anticipación.",
          "Fx Lab no es responsable por daños indirectos o consecuentes derivados del uso del sitio web o bot entregado. Los entregables se proveen tal cual una vez aceptados.",
          "Para preguntas sobre estos términos, escribe al contacto indicado abajo.",
        ],
      },
      privacy: {
        title: "Política de Privacidad",
        updated: "Última actualización: septiembre de 2026",
        body: [
          "Esta página explica qué información recoge el formulario de contacto y cómo se usa.",
          "Al enviar el formulario de contacto recopilamos tu nombre, el medio de contacto que indiques (teléfono, WhatsApp o correo), el tipo de negocio y el mensaje que escribas.",
          "Esa información se envía directamente por correo a Felix para responder tu consulta. No se vende, no se comparte con anunciantes ni se usa para otro fin que no sea responderte y, si te conviertes en cliente, entregar el servicio acordado.",
          "Usamos analítica sin cookies y respetuosa con la privacidad (Vercel Web Analytics) para entender en conjunto cómo los visitantes llegan y usan el sitio. No te rastrea por la web, no usa cookies y no recopila información que te identifique personalmente. Medimos visitas agregadas y algunas acciones de conversión (por ejemplo, un clic en un botón de WhatsApp o el envío del formulario de contacto) para saber qué vale la pena mejorar.",
          "Para solicitar la eliminación de tu información, contacta a Felix por WhatsApp o correo usando los datos del pie de página, y será eliminada de nuestros registros.",
        ],
      },
    },
    language: "English",
  },
} as const;

export function getContent(locale: Locale) {
  return content[locale];
}

export const brand = content.en.brand;
export const spanishWelcome = content.en.hero.welcome;
export const about = { name: "Felix", bio: content.en.about.bio };

export const whatsappHref = "https://wa.me/16197452934";
export const businessPhone = "+16197452934";
export const businessEmail = "felix.44802@gmail.com";
export const siteOrigin = "https://fx-labs-website.vercel.app";


