import type { Locale } from "./locale";

export type SiteContent = ReturnType<typeof getContent>;

const content = {
  en: {
    brand: { name: "Fx Labs", tagline: "A digital presence that answers for itself." },
    nav: {
      home: "Home",
      about: "About",
      services: "Services",
      benefits: "Benefits",
      pricing: "Pricing",
      contact: "Contact",
      cta: "Get Started",
      tryDemo: "Try Demo",
      switchLanguageTitle: "Switch Language",
    },
    hero: {
      headline: "The Future of Local Business with Latest AI Technology",
      description: "Expert AI tech to elevate your business operations and inquiries. Let's take your revenue and digital presence further.",
      getStarted: "Get Started",
      tryDemo: "Try Demo",
      ratingScore: "5.0",
      ratingText: "from 80+ reviews",
      welcome: "Se habla español · We speak Spanish too",
      bento: {
        clientsCount: "100+",
        clientsLabel: "Our Esteemed Clients & Partners",
        projectsCount: "1951+",
        projectsLabel: "Total Inquiries Handled",
        projectsPill: "8% monthly growth",
        yearsCount: "6+",
        yearsLabel: "Years of Dedicated Tech Experience",
        efficiencyTitle: "Achieve Optimal Efficiency and Boost Productivity",
      },
    },
    servicesHeading: "Efficient and Integrated Automation Services",
    servicesSubheading: "Simplify operations with our efficient, quality-focused AI services.",
    bentoServices: [
      {
        id: "website",
        title: "Website Design & Assembly",
        description: "Engineered with AI speed, handcrafted with precision. Zero generic AI slop or cheap templates — custom, ultra-fast architectures designed to convert.",
      },
      {
        id: "bot",
        title: "Custom WhatsApp Bots",
        description: "Intelligent AI agents trained on your business data. Answering inquiries, scheduling confirmed appointments, and closing sales 24/7.",
      },
      {
        id: "leads",
        title: "Targeted Lead Generation",
        description: "Automated acquisition funnels delivering high-intent, pre-qualified clients straight to your inbox and WhatsApp.",
      },
      {
        id: "tech",
        title: "Technology & AI Innovation",
        description: "Cutting-edge LLM pipelines and custom automations built specifically for your business workflow.",
      },
      {
        id: "sync",
        title: "Automated CRM & Sync",
        description: "Instant data routing to Google Calendar, CRM, Stripe, and email without manual entry.",
      },
      {
        id: "consulting",
        title: "Strategic Growth Consulting",
        description: "Direct 1-on-1 engineering support to identify bottlenecks, streamline operations, and scale your digital presence.",
      },
    ],
    servicesBento: {
      badge: "CORE CAPABILITIES",
      flagshipBadge: "FLAGSHIP SERVICE",
      lighthouseScore: "Google Lighthouse Score",
      subSecondLoad: "⚡ Sub-second load time (<0.4s) • Zero AI Slop",
      activeBadge: "24/7 ACTIVE",
      chatCustomerMsg: "Hey! Are there any appointments available today?",
      chatBotReply: "Hi! Yes, we have 4:00 PM open. Booked & confirmed ✅",
      autoBookLabel: "AI Auto-Book",
      convBadge: "↗ +45% CONV",
      inboundFlowLabel: "Inbound Flow",
      prequalifiedLabel: "100% Pre-qualified",
      engineBadge: "GPT-4o ENGINE",
      modelLatencyLabel: "Model Latency",
      autoPipelineBadge: "AUTO PIPELINE",
      waLeadLabel: "WA Lead",
      calendarLabel: "Calendar",
      oneOnOneBadge: "1-ON-1 DIRECT",
      talkToFounder: "Talk to Founder",
    },
    statsStrip: {
      aiPoweredCore: "AI Powered Core",
    },
    benefits: {
      heading: "Key Benefits of Our System for Your Business Efficiency",
      subheading: "Our systems boost productivity, cut labor costs, and drive predictable business growth.",
      totalInquiriesLabel: "Total Inquiries ↗ 8%",
      stats: {
        totalTitle: "Total Projects",
        totalNumber: "1475",
        growth: "14%",
        finished: "Finished",
        finishedVal: "92%",
        inProgress: "In-Progress",
        inProgressVal: "13%",
        reported: "Reported",
        reportedVal: "5%",
        activeLeadsCount: "1951+",
        activeLeadsText: "Increase of 12% this month",
      },
      pillars: [
        {
          title: "Boosting Quality with Tech",
          description: "With advanced AI technology, we help you achieve top-tier customer response quality. Discover how we elevate your service standard.",
        },
        {
          title: "Optimization Production Process",
          description: "Boost business efficiency and customer satisfaction with our bespoke bots and high-speed web infrastructure.",
        },
        {
          title: "AI-Driven Growth",
          description: "Leverage the power of AI to transform your business inquiries, achieving faster replies and more confirmed bookings.",
        },
      ],
    },
    pricing: {
      badge: "TRANSPARENT VALUE",
      heading: "Simple Pricing & Tailored Packages",
      subheading: "Choose a standalone website or get your custom site included free ($0 setup) with our monthly AI Bot / Voice Agent service.",
      starter: {
        name: "Standalone Custom Website",
        desc: "Essential digital presence for business owners who just need an ultra-fast, high-converting website.",
        price: "$500",
        priceDetail: "one-time (+ $10-15/mo domain & hosting)",
        features: [
          "Handcrafted high-speed website (Zero AI slop)",
          "Google Lighthouse 99+ speed score",
          "Mobile-first conversion design & SEO",
          "Direct WhatsApp lead routing button",
          "Includes 30 days post-launch support",
        ],
        cta: "Get My Website",
      },
      partner: {
        name: "The AI Growth Partner",
        desc: "Our most popular package. When you partner with our monthly AI Bot or Voice Agent service, we build your $500 website for $0 setup fee.",
        price: "Low Monthly Retainer",
        priceDetail: "Custom quote based on volume",
        badge: "🎁 $500 WEBSITE INCLUDED FREE ($0 SETUP)",
        features: [
          "Complete $500 Custom Website ($0 setup)",
          "24/7 WhatsApp AI Bot or Voice Chat Agent",
          "Automated appointment booking & CRM sync",
          "Continuous AI prompt tuning & maintenance",
          "Direct 1-on-1 engineer priority support",
        ],
        cta: "Claim Free Website with Bot",
      },
      configurator: {
        title: "Or Build Your Custom Package",
        subtitle: "Select the tools your business needs and get a transparent, custom quote directly on WhatsApp in minutes.",
        cta: "Get Custom Quote on WhatsApp",
        modules: [
          { id: "web", name: "Custom Engineered Website", desc: "$500 standalone or $0 with Monthly Bot", defaultChecked: true },
          { id: "whatsapp", name: "24/7 WhatsApp AI Bot", desc: "Instant FAQ, lead qualification & booking", defaultChecked: true },
          { id: "voice", name: "AI Voice Chat Agent", desc: "Phone call answering & voice appointment booking", defaultChecked: false },
          { id: "crm", name: "CRM & Calendar Sync", desc: "Google Calendar, Stripe & contact routing", defaultChecked: true },
          { id: "leads", name: "Targeted Inbound Funnel", desc: "Meta/Ads traffic optimization", defaultChecked: false },
        ],
      },
      standaloneLabel: "Standalone",
      includedLabel: "What's Included",
      partnerBenefitsLabel: "Partner Benefits",
      configuratorBadge: "INTERACTIVE CONFIGURATOR",
      modulesSelectedSuffix: "selected in your package",
      starterWhatsappText: "Hi Felix! I'm interested in the Standalone Custom Website ($500).",
      partnerWhatsappText: "Hi Felix! I'm interested in the AI Growth Partner package with the free website setup.",
      customWhatsappGreetingPrefix: "Hello Felix! I'm on your website and would like a custom package quote for my business. I'm interested in: ",
      customWhatsappGreetingSuffix: ".",
      defaultPackageLabel: "a custom package",
    },
    integrations: {
      heading: "Empowering Top Companies with Seamless Integrations",
      subheading: "Experience seamless connections with our innovative AI solutions, designed to effortlessly integrate with your existing systems and drive greater success.",
      cta: "Work With Us",
      badge: "NEURAL DATA FLOW",
      activeLabel: "Active",
      hoverHint: "Hover over each integration to see the data flow",
      items: {
        whatsapp: { role: "24/7 AI Sales & Lead Capture", badge: "Official API" },
        openai: { role: "Intelligent Reasoning Core", badge: "LLM Brain" },
        stripe: { role: "Instant Checkout & Subscriptions", badge: "Auto-Invoicing" },
        calendar: { role: "Automatic Meeting Booking", badge: "Auto-Sync" },
        meta: { role: "Lead Generation Pipeline", badge: "Traffic Flow" },
        crm: { role: "Centralized Client Database", badge: "Instant Sync" },
      },
    },
    ctaBanner: {
      heading: "From Idea to Production in Days",
      subheading: "Accelerate your customer acquisition with our technology. Reduce downtime and optimize costs. Get a tailored offer today!",
      cta: "Work With Us",
    },
    about: {
      eyebrow: "Behind the Systems",
      heading: "About Felix",
      role: "Founder & Automation Specialist",
      bio: "I build AI-powered websites, custom WhatsApp bots, and lead systems for business owners who are too busy delivering great service to spend hours answering repetitive messages. Direct collaboration, zero middleman.",
      directAccessLabel: "Direct Access",
      directAccessBody: "Work directly with the builder, zero account manager middleman.",
    },
    contact: {
      eyebrow: "Start Your Journey",
      directLine: "Direct Line",
      instantChatTitle: "Prefer instant chat?",
      instantChatBody: "Skip the form and message Felix directly on WhatsApp for an immediate response.",
      openWhatsapp: "Open WhatsApp",
      heading: "Let's Build Your Digital Presence",
      subheading: "Ready to automate your inquiries and turn site traffic into booked clients? Send a message below or chat directly on WhatsApp.",
      welcome: "Se habla español · We speak Spanish too",
      name: "Name",
      contact: "Phone, WhatsApp, or email",
      businessType: "Business type",
      options: ["Restaurant", "Shop", "Contractor", "Other"],
      message: "Message",
      send: "Send",
      sending: "Sending...",
      success: "Thanks — I'll get back to you soon.",
      deliveryFailed: "Your message didn't go through. Please try again, or message Felix directly on WhatsApp.",
      formError: "Please fix the highlighted fields.",
      errors: {
        name: "Name is required",
        contact: "Enter a valid phone number or email",
        businessType: "Business type is required",
        message: "Please add a short message",
      },
    },
    footer: {
      tagline: "Our systems make your digital presence faster, smarter, and always online.",
      companyTitle: "Company",
      companyLinks: ["About Us", "Customers"],
      servicesTitle: "Services",
      servicesLinks: ["Website Engineering", "WhatsApp Bots", "Lead Generation", "AI Integrations"],
      getInTouchTitle: "Get in Touch",
      directWhatsapp: "Direct WhatsApp",
      callTitle: "Call",
      emailTitle: "Email",
      serviceArea: "San Diego · South Bay",
      terms: "Terms & Conditions",
      privacy: "Privacy Policy",
      copyright: `© ${new Date().getFullYear()} Fx Labs. All rights reserved.`,
    },
    bentoServicesCta: "Chat on WhatsApp",
    legal: {
      terms: {
        title: "Terms & Conditions",
        updated: "Last updated: September 2026",
        body: [
          "By submitting the contact form or hiring Fx Labs, you agree to these terms.",
          "Fx Labs designs and builds websites, WhatsApp bots, and related automation for local businesses. Project scope, pricing, and delivery timelines are agreed directly with Felix before work begins.",
          "One-time website packages include 30 days of post-launch support. Monthly retainer services (AI bots, voice agents) renew month to month and can be cancelled with notice via WhatsApp or email.",
          "Payments are due as agreed at project kickoff. Domain, hosting, and third-party subscription costs (if any) are billed separately and disclosed up front.",
          "Fx Labs is not liable for indirect or consequential damages arising from use of the delivered website or bot. Deliverables are provided as-is after acceptance testing.",
          "Questions about these terms can be sent to the contact below.",
        ],
      },
      privacy: {
        title: "Privacy Policy",
        updated: "Last updated: September 2026",
        body: [
          "This page explains what information the contact form collects and how it's used.",
          "When you submit the contact form, we collect your name, the contact method you provide (phone, WhatsApp, or email), your business type, and any message you write.",
          "That information is emailed directly to Felix to respond to your inquiry. It is not sold, shared with advertisers, or used for any purpose beyond replying to you and, if you become a client, delivering the agreed service.",
          "We do not use cookies or analytics trackers on this site beyond what's required for the site to function.",
          "To request deletion of your information, contact Felix by WhatsApp or email using the details in the footer, and it will be removed from our records.",
        ],
      },
    },
    language: "Español",
  },
  es: {
    brand: { name: "Fx Labs", tagline: "Una presencia digital que responde por sí sola." },
    nav: {
      home: "Inicio",
      about: "Sobre Mí",
      services: "Servicios",
      benefits: "Beneficios",
      pricing: "Planes",
      contact: "Contacto",
      cta: "Comenzar",
      tryDemo: "Ver Demo",
      switchLanguageTitle: "Cambiar Idioma",
    },
    hero: {
      headline: "El Futuro de los Negocios Locales con Tecnología IA",
      description: "Tecnología de IA de vanguardia para elevar las operaciones y consultas de tu negocio. Llevemos tus ingresos y presencia digital al siguiente nivel.",
      getStarted: "Comenzar",
      tryDemo: "Ver Demo",
      ratingScore: "5.0",
      ratingText: "de más de 80 reseñas",
      welcome: "We speak English too · También hablamos español",
      bento: {
        clientsCount: "100+",
        clientsLabel: "Nuestros Clientes y Aliados",
        projectsCount: "1951+",
        projectsLabel: "Consultas y Leads Procesados",
        projectsPill: "8% crecimiento mensual",
        yearsCount: "6+",
        yearsLabel: "Años de Experiencia en Automatización",
        efficiencyTitle: "Alcanza la Máxima Eficiencia y Productividad",
      },
    },
    servicesHeading: "Servicios de Automatización Eficientes e Integrados",
    servicesSubheading: "Simplifica tus operaciones con nuestros servicios de IA enfocados en la calidad y conversión.",
    bentoServices: [
      {
        id: "website",
        title: "Diseño y Creación Web",
        description: "Ingeniería web de alto rendimiento con IA. Cero plantillas genéricas o 'AI slop' — arquitecturas ultra veloces hechas a medida para convertir.",
      },
      {
        id: "bot",
        title: "Bots Personalizados de WhatsApp",
        description: "Agentes inteligentes entrenados con tus datos que responden dudas, agendan citas confirmadas y cierran ventas 24/7.",
      },
      {
        id: "leads",
        title: "Generación de Leads Calificados",
        description: "Embudos automatizados de alta intención que envían clientes pre-calificados directo a tu WhatsApp.",
      },
      {
        id: "tech",
        title: "Tecnología e Innovación IA",
        description: "Pipelines de LLM de última generación y automatizaciones creadas a la medida de tu negocio.",
      },
      {
        id: "sync",
        title: "Sincronización de CRM y Calendario",
        description: "Enrutamiento automático de datos a Google Calendar, CRM, Stripe y correo sin trabajo manual.",
      },
      {
        id: "consulting",
        title: "Consultoría Estratégica de Crecimiento",
        description: "Asesoría directa 1 a 1 para eliminar cuellos de botella, optimizar procesos y escalar tu presencia digital.",
      },
    ],
    servicesBento: {
      badge: "CAPACIDADES CLAVE",
      flagshipBadge: "SERVICIO INSIGNIA",
      lighthouseScore: "Puntuación Google Lighthouse",
      subSecondLoad: "⚡ Carga en menos de 0.4s • Cero 'AI slop'",
      activeBadge: "24/7 ACTIVO",
      chatCustomerMsg: "¡Hola! ¿Tienen citas disponibles hoy?",
      chatBotReply: "¡Hola! Sí, tenemos las 4:00 PM libres. Reservado y confirmado ✅",
      autoBookLabel: "Auto-Reserva IA",
      convBadge: "↗ +45% CONV",
      inboundFlowLabel: "Flujo de Entrada",
      prequalifiedLabel: "100% Precalificado",
      engineBadge: "MOTOR GPT-4o",
      modelLatencyLabel: "Latencia del Modelo",
      autoPipelineBadge: "PIPELINE AUTOMÁTICO",
      waLeadLabel: "Lead WA",
      calendarLabel: "Calendario",
      oneOnOneBadge: "1 A 1 DIRECTO",
      talkToFounder: "Habla con el Fundador",
    },
    statsStrip: {
      aiPoweredCore: "Núcleo con IA",
    },
    benefits: {
      heading: "Beneficios Clave de Nuestro Sistema para tu Negocio",
      subheading: "Nuestros sistemas aumentan la productividad, reducen costos y generan crecimiento predecible.",
      totalInquiriesLabel: "Consultas Totales ↗ 8%",
      stats: {
        totalTitle: "Total Proyectos",
        totalNumber: "1475",
        growth: "14%",
        finished: "Completados",
        finishedVal: "92%",
        inProgress: "En Proceso",
        inProgressVal: "13%",
        reported: "Reportados",
        reportedVal: "5%",
        activeLeadsCount: "1951+",
        activeLeadsText: "Aumento del 12% este mes",
      },
      pillars: [
        {
          title: "Impulso de Calidad con Tecnología",
          description: "Con tecnología avanzada de IA te ayudamos a brindar una atención al cliente de primer nivel al instante.",
        },
        {
          title: "Optimización de Procesos",
          description: "Aumenta la eficiencia y satisfacción de tus clientes con bots a la medida e infraestructura web rápida.",
        },
        {
          title: "Crecimiento Impulsado por IA",
          description: "Aprovecha el poder de la IA para transformar tus consultas en citas y ventas confirmadas en automático.",
        },
      ],
    },
    pricing: {
      badge: "VALOR TRANSPARENTE",
      heading: "Precios Transparentes y Paquetes a Medida",
      subheading: "Elige solo tu sitio web o llévatelo incluido gratis ($0 de instalación) al contratar nuestro servicio mensual de Chatbot o Agente de Voz.",
      starter: {
        name: "Sitio Web Independiente",
        desc: "Presencia digital esencial para dueños de negocios que solo necesitan una web ultra rápida que convierta.",
        price: "$500",
        priceDetail: "pago único (+ $10-15/mes dominio y hosting)",
        features: [
          "Diseño web de alto rendimiento (Cero plantillas basura)",
          "Puntuación Google Lighthouse 99+",
          "Diseño móvil y optimización SEO local",
          "Botón de contacto directo a WhatsApp",
          "Incluye 30 días de soporte post-lanzamiento",
        ],
        cta: "Quiero mi Sitio Web",
      },
      partner: {
        name: "Socio de Crecimiento IA",
        desc: "Nuestro paquete más solicitado. Al contratar nuestro servicio mensual de Chatbot o Agente de Voz, te diseñamos y montamos la web de $500 totalmente gratis.",
        price: "Mensualidad Accesible",
        priceDetail: "Cotización según tu volumen",
        badge: "🎁 SITIO WEB DE $500 INCLUIDO GRATIS ($0 SETUP)",
        features: [
          "Sitio web completo de $500 ($0 instalación)",
          "Bot de WhatsApp 24/7 o Agente de Voz telefónico",
          "Agendamiento automático de citas y sincronización CRM",
          "Mantenimiento y mejora continua de la IA",
          "Soporte técnico directo 1 a 1 con el creador",
        ],
        cta: "Reclamar Web Gratis con Bot",
      },
      configurator: {
        title: "O Diseña Tu Propio Paquete a Medida",
        subtitle: "Selecciona las herramientas que necesita tu negocio y recibe una cotización transparente por WhatsApp en minutos.",
        cta: "Pedir Cotización en WhatsApp",
        modules: [
          { id: "web", name: "Sitio Web a Medida", desc: "$500 solo o $0 con Bot Mensual", defaultChecked: true },
          { id: "whatsapp", name: "Bot de WhatsApp 24/7", desc: "Respuestas inmediatas, calificación y citas", defaultChecked: true },
          { id: "voice", name: "Agente de Voz IA", desc: "Atención de llamadas telefónicas y agendamiento", defaultChecked: false },
          { id: "crm", name: "Sincronización CRM y Calendario", desc: "Google Calendar, Stripe y base de datos", defaultChecked: true },
          { id: "leads", name: "Embudos de Adquisición", desc: "Tráfico de anuncios y captación de clientes", defaultChecked: false },
        ],
      },
      standaloneLabel: "Independiente",
      includedLabel: "Qué Incluye",
      partnerBenefitsLabel: "Beneficios del Socio",
      configuratorBadge: "CONFIGURADOR INTERACTIVO",
      modulesSelectedSuffix: "seleccionados en tu paquete",
      starterWhatsappText: "¡Hola Felix! Me interesa el Sitio Web Independiente ($500).",
      partnerWhatsappText: "¡Hola Felix! Me interesa el paquete Socio de Crecimiento IA con el sitio web gratis.",
      customWhatsappGreetingPrefix: "¡Hola Felix! Estoy en tu sitio web y me gustaría una cotización de paquete personalizado para mi negocio. Me interesa: ",
      customWhatsappGreetingSuffix: ".",
      defaultPackageLabel: "un paquete personalizado",
    },
    integrations: {
      heading: "Potenciando Negocios con Integraciones Fluidas",
      subheading: "Conecta sin esfuerzo tus sistemas actuales con nuestras soluciones de IA para aumentar la productividad y el éxito de tu negocio.",
      cta: "Trabaja con Nosotros",
      badge: "FLUJO NEURAL DE DATOS",
      activeLabel: "Activo",
      hoverHint: "Pasa el cursor sobre cada integración para ver el flujo de datos",
      items: {
        whatsapp: { role: "Ventas IA y Captación de Leads 24/7", badge: "API Oficial" },
        openai: { role: "Núcleo de Razonamiento IA", badge: "Cerebro LLM" },
        stripe: { role: "Pagos y Suscripciones Instantáneos", badge: "Facturación Automática" },
        calendar: { role: "Agendamiento Automático de Citas", badge: "Auto-Sincronización" },
        meta: { role: "Embudo de Generación de Leads", badge: "Flujo de Tráfico" },
        crm: { role: "Base de Datos Centralizada de Clientes", badge: "Sincronización Instantánea" },
      },
    },
    ctaBanner: {
      heading: "De la Idea a la Producción en Días",
      subheading: "Acelera la adquisición de clientes con nuestra tecnología. Reduce tiempos muertos y optimiza costos.",
      cta: "Trabaja con Nosotros",
    },
    about: {
      eyebrow: "Detrás de los Sistemas",
      heading: "Sobre Felix",
      role: "Fundador y Especialista en Automatización",
      bio: "Creo sitios web con IA, bots de WhatsApp y sistemas de captación para dueños de negocios que están demasiado ocupados como para pasar horas respondiendo mensajes repetitivos. Trato directo, sin intermediarios.",
      directAccessLabel: "Acceso Directo",
      directAccessBody: "Trabaja directo con el creador, sin intermediarios ni gerentes de cuenta.",
    },
    contact: {
      eyebrow: "Comienza tu Camino",
      directLine: "Línea Directa",
      instantChatTitle: "¿Prefieres chat instantáneo?",
      instantChatBody: "Omite el formulario y escríbele a Felix directo por WhatsApp para una respuesta inmediata.",
      openWhatsapp: "Abrir WhatsApp",
      heading: "Construyamos Tu Presencia Digital",
      subheading: "¿Listo para automatizar tus consultas y convertir visitas en clientes? Envía un mensaje abajo o chatea directo por WhatsApp.",
      welcome: "We speak English too · También hablamos español",
      name: "Nombre",
      contact: "Teléfono, WhatsApp o correo",
      businessType: "Tipo de negocio",
      options: ["Restaurante", "Tienda", "Contratista", "Otro"],
      message: "Mensaje",
      send: "Enviar",
      sending: "Enviando...",
      success: "Gracias, te responderé pronto.",
      deliveryFailed: "Tu mensaje no se pudo enviar. Inténtalo de nuevo o escríbele a Felix directo por WhatsApp.",
      formError: "Corrige los campos marcados.",
      errors: {
        name: "El nombre es obligatorio",
        contact: "Ingresa un teléfono o correo válido",
        businessType: "El tipo de negocio es obligatorio",
        message: "Agrega un mensaje breve",
      },
    },
    footer: {
      tagline: "Nuestros sistemas hacen que tu presencia digital sea más rápida, inteligente y siempre activa.",
      companyTitle: "Empresa",
      companyLinks: ["Sobre Mí", "Clientes"],
      servicesTitle: "Servicios",
      servicesLinks: ["Ingeniería Web", "Bots de WhatsApp", "Generación de Leads", "Integraciones IA"],
      getInTouchTitle: "Contacto",
      directWhatsapp: "WhatsApp Directo",
      callTitle: "Llamar",
      emailTitle: "Correo",
      serviceArea: "San Diego · South Bay",
      terms: "Términos y Condiciones",
      privacy: "Política de Privacidad",
      copyright: `© ${new Date().getFullYear()} Fx Labs. Todos los derechos reservados.`,
    },
    bentoServicesCta: "Hablar por WhatsApp",
    legal: {
      terms: {
        title: "Términos y Condiciones",
        updated: "Última actualización: septiembre de 2026",
        body: [
          "Al enviar el formulario de contacto o contratar a Fx Labs, aceptas estos términos.",
          "Fx Labs diseña y construye sitios web, bots de WhatsApp y automatizaciones relacionadas para negocios locales. El alcance, precio y tiempos de entrega de cada proyecto se acuerdan directamente con Felix antes de comenzar el trabajo.",
          "Los paquetes de sitio web de pago único incluyen 30 días de soporte post-lanzamiento. Los servicios mensuales (bots de IA, agentes de voz) se renuevan mes a mes y pueden cancelarse avisando por WhatsApp o correo.",
          "Los pagos se realizan según lo acordado al inicio del proyecto. Costos de dominio, hosting o suscripciones de terceros (si aplican) se facturan por separado y se informan con anticipación.",
          "Fx Labs no es responsable por daños indirectos o consecuentes derivados del uso del sitio web o bot entregado. Los entregables se proveen tal cual una vez aceptados.",
          "Para preguntas sobre estos términos, escribe al contacto indicado abajo.",
        ],
      },
      privacy: {
        title: "Política de Privacidad",
        updated: "Última actualización: septiembre de 2026",
        body: [
          "Esta página explica qué información recoge el formulario de contacto y cómo se usa.",
          "Al enviar el formulario de contacto recopilamos tu nombre, el medio de contacto que indiques (teléfono, WhatsApp o correo), el tipo de negocio y el mensaje que escribas.",
          "Esa información se envía directamente por correo a Felix para responder tu consulta. No se vende, no se comparte con anunciantes ni se usa para otro fin que no sea responderte y, si te conviertes en cliente, entregar el servicio acordado.",
          "No usamos cookies ni rastreadores de analítica en este sitio más allá de lo necesario para su funcionamiento.",
          "Para solicitar la eliminación de tu información, contacta a Felix por WhatsApp o correo usando los datos del pie de página, y será eliminada de nuestros registros.",
        ],
      },
    },
    language: "English",
  },
} as const;

export function getContent(locale: Locale) {
  return content[locale];
}

export const brand = content.en.brand;
export const spanishWelcome = content.en.hero.welcome;
export const about = { name: "Felix", bio: content.en.about.bio };

export const whatsappHref = "https://wa.me/16197452934";
export const businessPhone = "+16197452934";
export const businessEmail = "felix.44802@gmail.com";
export const siteOrigin = "https://fx-labs-website.vercel.app";


